title: Music Theory Companion
description: Helping musicians shine

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

include:
  - README.md
  - privacy_policy.md
  - terms_of_service.md

# Pages for which links are shown at the menu
pages_in_toolbar:
- title: Home
  url: .

- title: Privacy Policy
  url: privacy_policy.html

- title: Terms of Service
  url: terms_of_service.html

# Website theme
theme: jekyll-theme-cayman

safe: true

# Disable "View on GitHub" button
github:
  is_project_page: false
